development:
  api_key: <%= ENV['SHOPIFY_APP_API_KEY'] %>
  secret: <%= ENV['SHOPIFY_APP_API_SECRET'] %>

test:
  api_key: <%= ENV['SHOPIFY_APP_API_KEY'] %>
  secret: <%= ENV['SHOPIFY_APP_API_SECRET'] %>